### PR TITLE
Feature/63 configure lambdas for running layers

### PR DESCRIPTION
**Pull request by tungtongduc**
- create deploy script for layers
- adjust deploy script for lambdas
- remapping path of lambdas for running with layers
- convert tests to jest style :)

### CODE REVIEW

**Comment by tungtongduc** [comment]
Sorry that this pull request is too large. The reason is: the lambda's deploy script was adjusted, (to map lambda with layers) => all lambdas muss be also changed, so that they can work with layers
I tried to change old tests using jest framework, but their logic/funktionalities stay unchanged.

**Comment by meteohr** [comment]
@tungtongduc Can you explain the new workflow a bit with this change? If you update anything under `commons` it must be deployed as a new layer version, correct? And if this happens we need to adapt the variable `currentLayerVersion` in lambda deploy script as well, right?
Also how does local development work?

**Comment by tungtongduc** [comment]
yes, correct! i described it in README.
local development stays the same as before. It's important, that all import-path from common should start with "/opt/nodejs/", but i configured it already in ts-config.json, so that IDE does it automatically for us (auto-import).

**Comment by izi01** [comment]
Looks good, thanks for your work 👍 


I see one problem here and its forgetting to publish a new layer version after making changes to the commons modules and therefore deploying broken lambdas.

Maybe you have better idea but we could solve it like this:

- Let deploy-layers.sh return the updated version number.
- call deploy-layers.sh from deploy-lambda.sh and store the result in $currentLayerVersion
- or just make it a function in deploy-lambda, guess that is easier

That way we could be sure to have the correct layer setup. Downside is we would publish a new layer version everytime, even if it is not necessary. 

But I think thats not too bad. S3 space is cheap and we can clean up later. 
In a follow up task we could then store a md5 hash of the commons.zip in a text file and commit it during deployment. The next time the script runs it could compare the hashes after creating the commons.zip and, if they are equal, skip the upload and return currently publishes layer's version?

**Review by truefalse10 — APPROVED** [review]

**Review by izi01 — APPROVED** [review]

**Pull request merged**
